# Generated by Django 3.0.2 on 2020-01-27 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table='Blog',
        ),
    ]
