# Generated by Django 3.0.2 on 2020-01-28 07:34

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200127_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, unique=True, validators=[blog.models.mycustomvalidator, blog.models.val2]),
        ),
    ]
